chore(ci): Finish valgrind installation tests for different platforms

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -99,7 +99,7 @@ jobs:
       - name: Verify gungraun-runner
         run: gungraun-runner --version
 
-  test-valgrind:
+  test-basic-valgrind:
     needs: [format-and-lint, build]
     runs-on: ubuntu-latest
     strategy:
@@ -146,19 +146,20 @@ jobs:
         id: set_valgrind_version
         run: |
           if [[ "${{ matrix.valgrind-strategy }}" == "system" && -z "${{ matrix.valgrind-version }}" ]]; then
-            valgrind_version=$(./scripts/system-valgrind-version.sh)
-            echo "version=${valgrind_version}" >> $GITHUB_OUTPUT
+            valgrind_version="$(./scripts/system-valgrind-version.sh)"
+            echo "version=${valgrind_version}" >> "$GITHUB_OUTPUT"
           else
-            echo "version=${{ matrix.valgrind-version }}" >> $GITHUB_OUTPUT
+            echo "version=${{ matrix.valgrind-version }}" >> "$GITHUB_OUTPUT"
           fi
 
       - name: Detect the expected valgrind version
         id: get_valgrind_version
         run: |
           version="$(./scripts/expected-valgrind-version.sh "${{ matrix.valgrind-strategy }}" "${{ matrix.valgrind-version }}")"
-          echo "expected_version=${version}" >> $GITHUB_OUTPUT
+          echo "expected_version=${version}" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ github.token }}
+          # GUNGRAUN_ACTION_DEBUG: yes
 
       - name: Run action
         id: action
@@ -170,6 +171,8 @@ jobs:
           valgrind-version: ${{ steps.set_valgrind_version.outputs.version }}
           install-build-deps: ${{ matrix.install-build-deps }}
           github-token: ${{ github.token }}
+        # env:
+        #   GUNGRAUN_ACTION_DEBUG: yes
 
       - name: Verify valgrind on failure
         if: steps.action.outcome == 'failure'
@@ -199,6 +202,132 @@ jobs:
               exit 1
             else
               echo "Successfully installed valgrind: $actual_version"
+
+              set -x
+              # To verify the default gungraun tool is running
+              valgrind --tool=callgrind ls -la
+              # To verify the debug symbol installation for libc is working
+              valgrind --tool=memcheck ls -la
+
+              exit 0
+            fi
+          fi
+
+  test-valgrind-platforms:
+    needs: [format-and-lint, build]
+    runs-on: ubuntu-latest
+    container: ${{ matrix.container-image }}
+    strategy:
+      fail-fast: false
+      matrix:
+        strategy: ['system', 'source']
+        container-image:
+          # apt
+          - debian:bookworm-slim
+          - debian:trixie-slim
+          - ubuntu:22.04
+          - ubuntu:24.04
+          - ubuntu:26.04
+          # dnf/yum
+          - almalinux:9
+          - almalinux:9-minimal
+          - almalinux:10
+          - almalinux:10-minimal
+          - amazonlinux:latest
+          - fedora:latest
+          # apk
+          - alpine:3.22
+          - alpine:3.23
+          # pacman
+          - archlinux:latest
+          # zypper
+          - opensuse/leap:latest
+          - opensuse/tumbleweed:latest
+        include:
+          - install-build-deps: false
+          - strategy: source
+            install-build-deps: true
+    steps:
+      - name: Installs prerequisites
+        shell: sh
+        run: |
+          image="${{ matrix.container-image }}"
+
+          case "$image" in
+          ubuntu:* | debian:*)
+            apt-get update
+            apt-get install -y --no-install-recommends git ca-certificates
+            ;;
+          almalinux:*-minimal)
+            microdnf install -y tar git
+            ;;
+          almalinux:* | fedora* | amazonlinux*)
+            dnf install -y tar git
+            ;;
+          opensuse*)
+            zypper --non-interactive install tar gzip awk git
+            ;;
+          alpine*)
+            apk add git
+            ;;
+          archlinux*)
+            pacman -Sy --noconfirm git
+            ;;
+          *) ;;
+          esac
+
+      - uses: actions/checkout@v6
+      - name: Detect the expected valgrind version
+        shell: sh
+        id: get_valgrind_version
+        run: |
+          version="$(./scripts/expected-valgrind-version.sh \
+                   "${{ matrix.strategy }}" "auto")"
+          if [ "$version" = "none" ]; then
+            echo "Error in action tests: The version should not be none"
+            exit 1
+          else
+            echo "Detected version: '${version}'"
+            echo "expected_version=${version}" >> "$GITHUB_OUTPUT"
+          fi
+        env:
+          GH_TOKEN: ${{ github.token }}
+          # GUNGRAUN_ACTION_DEBUG: yes
+
+      - name: Run action
+        uses: ./
+        with:
+          runner-strategy: none
+          valgrind-strategy: ${{ matrix.strategy }}
+          valgrind-version: auto
+          install-build-deps: ${{ matrix.install-build-deps }}
+        # env:
+        #   GUNGRAUN_ACTION_DEBUG: yes
+
+      - name: Verify valgrind
+        shell: sh
+        run: |
+          expected_version="${{ steps.get_valgrind_version.outputs.expected_version }}"
+
+          if [ "$expected_version" = "none" ]; then
+            echo "Expected the action to fail but it succeeded" >&2
+            exit 1
+          else
+            actual_version="$(valgrind --version)"
+            if [ "$actual_version" != "valgrind-${expected_version}" ]; then
+              echo "Mismatch between expected valgrind version \
+                    'valgrind-${expected_version}' and actual version \
+                    '${actual_version}" >&2
+              exit 1
+            else
+              echo "Successfully installed valgrind: $actual_version"
+
+              set -x
+              # To verify the default gungraun tool is running
+              valgrind --tool=callgrind ls -la
+              # To verify the debug symbol installation for libc is working
+              valgrind --tool=memcheck ls -la
+
               exit 0
             fi
           fi
@@ -238,5 +367,12 @@ jobs:
             exit 1
           else
             echo "Successfully installed valgrind: $actual_version"
+
+            set -x
+            # To verify the default gungraun tool is running
+            valgrind --tool=callgrind ls -la
+            # To verify the debug symbol installation for libc is working
+            valgrind --tool=memcheck ls -la
+
             exit 0
           fi
